### ISSUE TITLE
Отсутсвует кнопка добавления счёта

### ISSUE THREAD

**Issue by inoyakaigor** [YoshiOne/fingen#12]
![image](https://user-images.githubusercontent.com/1235286/41101268-5fed3918-6a6c-11e8-9a1d-2aaf6a2a8140.png)

Highscreen Power Four
Android 5.1.1
Версия приложения последняя

**Comment by YoshiOne** [comment]
Прокрутите список вверх и потяните вверх нижнюю панель. Она там.

**Comment by inoyakaigor** [comment]
Иисусе! 😳
Я, признаться, ожидал стандартную круглую кнопку справа внизу. Как, например, на экране редактирования какого-либо справочника. (Это, кстати, говорит о неконсистентности интерфейса, но от бесплатной программы я этого и не жду)
