### ISSUE TITLE
Пакетное удаление данных

### ISSUE THREAD

**Issue by batlukov** [YoshiOne/fingen#15]
Это первый финансовый органайзер, которым я смог начать заставить себя пользоваться, хотя пробовал многое и даже делал андроид версию одного из (если интересно, ссылку скину, там на самом деле есть удобные вещи) :) В общем сейчас в процессе приучения себя к дисциплине. Иногда приходится начинать все заново. Не хватает пакетного удаления отфильтрованных транзакций, естественно с двойным подтверждением. Возможно также будет удобен мультиселект транзакций, и удаление уже его.

**Comment by YoshiOne** [comment]
Такая возможность есть, нажмите на значок (стрелку) транзакции для выделения, после чего появится меню с возможными действиями, в т.ч. возможностью удаления выделенных.

**Comment by YoshiOne** [comment]
Такая возможность есть, нажмите на значок (стрелку) транзакции для выделения, после чего появится меню с возможными действиями, в т.ч. возможностью удаления выделенных.
