### ISSUE TITLE
При попытке скачать чек illegal public api usage

### ISSUE THREAD

**Issue by Nebula100** [YoshiOne/fingen#28]
Похоже обновилось api y налоговой.

**Comment by ivang7** [comment]
Апи осталось прежним, оригинальный клиент выполняет 3 запроса:
1. проверка чека на валидность
2. проверка наличия данных в ФНС?!
3. повторное выполнение второго запроса возвращает непосредственно JSON:
![image](https://user-images.githubusercontent.com/10797493/50558903-c94eef80-0d02-11e9-9911-38e056e31daf.png)

Как минимум, можно попробовать воспроизвести те же последовательности запросов в программе.

**Comment by Nebula100** [comment]
Да да. Тут нет 1 запроса. Я попробовал проверить на валидность официальным приложением от налоговой. После этого программа получила чек без ошибок. (проверил на нескольких чеках)
