### ISSUE TITLE
Расхождение в Итого на разных экранах

### ISSUE THREAD

**Issue by w3d1** [YoshiOne/fingen#6]
Расходится сумма "Итого" на экранах "Счета" и "Транзакции" (в "Сводке так же как в "Транзакциях).
В транзакциях итоговая сумма меньше чем должна быть по факту.
В "счетах" сумма правильная.
Причем "Приход" и "Расход" - на всех экранах суммы сходятся.

**Comment by YoshiOne** [comment]
Во вкладке счета указывается итого ваших средств = начальные суммы на счетах + приход - расход. Во вкладке транзакции отображается только движение средств = приход - расход. Это объясняет разницу в ваших суммах?

**Comment by w3d1** [comment]
Спасибо, теперь ясно!
